### ISSUE TITLE
Segmentation fault for SHIFT and NARF methods

### ISSUE THREAD

**Issue by coreos-xx** [horizon-research/PointCloud-pipeline#2]
Hello, when I am using the NARF or SHIFT method in the config file I get :

`NARF Keypoints Are Being Detected!
Segmentation fault (core dumped)
`
in the terminal output. 
However, the HARRIS method seems to work fine. 
Do you have any ideas on what causes the program to crash? 
Thank you in advance

**Comment by power-rdx** [comment]
Hi, could you please provide more details?
NARF was what we primarily used for testing, so I guess it might be a version issue

**Comment by power-rdx** [comment]
Hi @coreos-xx,

If you don't have further questions, I will close this issue in three days.

Best regards,
Boyuan Tian

**Comment by Boyuan-Tian** [comment]
Close the issue due to no further questions.

**Comment by hanm2019** [comment]
@Boyuan-Tian I meet the same problem after I clone the code and `make`, `./pc_pipeline` with the default config.txt
![image](https://user-images.githubusercontent.com/56673361/145149278-0ab6279c-a3c6-4d00-858b-1c65d87f8da8.png)

the version is :
```
os: ubuntu 18.04
pcl: 1.12
gcc: 7.5.0
```
